// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

using UnityEngine;

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Network.Messages
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class PlayerSpawnMessageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Network.Messages.PlayerSpawnMessage>
    {


        public void Serialize(ref MessagePackWriter writer, global::Network.Messages.PlayerSpawnMessage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.LocalPlayerPosition, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.LocalPlayerNickname, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<uint, string>>().Serialize(ref writer, value.NetPlayers, options);
            writer.Write(value.PeerID);
            writer.Write(value.IsBroadcast);
        }

        public global::Network.Messages.PlayerSpawnMessage Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __LocalPlayerPosition__ = default(Vector3);
            var __LocalPlayerNickname__ = default(string);
            var __NetPlayers__ = default(global::System.Collections.Generic.Dictionary<uint, string>);
            var __IsBroadcast__ = default(bool);
            var __PeerID__ = default(uint);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __LocalPlayerPosition__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __LocalPlayerNickname__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __NetPlayers__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<uint, string>>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __IsBroadcast__ = reader.ReadBoolean();
                        break;
                    case 3:
                        __PeerID__ = reader.ReadUInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Network.Messages.PlayerSpawnMessage(__LocalPlayerPosition__, __LocalPlayerNickname__, __NetPlayers__, __PeerID__);
            ____result.PeerID = __PeerID__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
