// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Network.Messages
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ConnectionMessageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Network.Messages.ConnectionMessage>
    {


        public void Serialize(ref MessagePackWriter writer, global::Network.Messages.ConnectionMessage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            formatterResolver.GetFormatterWithVerify<global::Players.SerializablePlayer>().Serialize(ref writer, value.Player, options);
            writer.Write(value.MessageCode);
            writer.Write(value.IsBroadcast);
            writer.Write(value.PeerID);
        }

        public global::Network.Messages.ConnectionMessage Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Player__ = default(global::Players.SerializablePlayer);
            var __MessageCode__ = default(byte);
            var __IsBroadcast__ = default(bool);
            var __PeerID__ = default(uint);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Player__ = formatterResolver.GetFormatterWithVerify<global::Players.SerializablePlayer>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __MessageCode__ = reader.ReadByte();
                        break;
                    case 2:
                        __IsBroadcast__ = reader.ReadBoolean();
                        break;
                    case 3:
                        __PeerID__ = reader.ReadUInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Network.Messages.ConnectionMessage(__Player__);
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
